name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: "nix"

    steps:
    - uses: "actions/checkout@v3"
    - uses: "cachix/install-nix-action@master"
      with:
        github_access_token: "${{ secrets.GITHUB_TOKEN }}"
    - name: "Build"
      run: |
        nix build '.#system-manager'
    - name: "Run tests"
      run: |
        nix flake check
